"""Caption style/preset definitions and normalization helpers."""

from typing import Any

from services.models.caption import (
    CaptionPreset,
    CaptionPresetDefinition,
    CaptionTemplate,
)

CAPTION_STYLE_ALIASES = {
    "animated": "animated",
    "karaoke": "animated",
    "static": "static",
    "classic": "static",
    "block": "static",
    "plain": "static",
    "grouped": "grouped",
    "lines": "grouped",
    "line_by_line": "grouped",
    "minimal": "grouped",
    "word_by_word": "word_by_word",
    "word": "word_by_word",
    "per_word": "word_by_word",
    "focus_word": "word_by_word",
    "progressive": "progressive",
    "build": "progressive",
    "typing": "progressive",
    "two_line": "two_line",
    "split": "two_line",
    "punctuated": "punctuated",
    "sentence": "punctuated",
    "uppercase": "uppercase",
    "caps": "uppercase",
    "lowercase": "lowercase",
    "lower": "lowercase",
    "headline": "headline",
    "title_case": "headline",
}
SUPPORTED_CAPTION_STYLES = {
    "animated",
    "static",
    "grouped",
    "word_by_word",
    "progressive",
    "two_line",
    "punctuated",
    "uppercase",
    "lowercase",
    "headline",
}

_FONT_CASES = {"as_typed", "uppercase", "lowercase", "headline"}

ANIMATION_ALIASES = {
    "none": "none",
    "bounce": "bounce",
    "underline": "underline",
    "box": "box",
    "pop": "pop",
    "scale": "scale",
    "slide_left": "slide_left",
    "slide up": "slide_up",
    "slide_up": "slide_up",
    "seamless_bounce": "seamless_bounce",
    "highlighter_box_around": "highlighter_box_around",
    "blur_switch": "blur_switch",
    "baby_earthquake": "baby_earthquake",
    "glitch_infinite_zoom": "glitch_infinite_zoom",
    "focus": "focus",
    "blur_in": "blur_in",
    "with_backdrop": "with_backdrop",
    "soft_landing": "soft_landing",
    "baby_steps": "baby_steps",
    "grow": "grow",
    "breathe": "breathe",
    # Friendly aliases used by social-caption presets.
    "karaoke_sweep": "karaoke_sweep",
    "typewriter": "typewriter",
    "neon_glow": "neon_glow",
    "conveyor_left": "conveyor_left",
    "punch": "punch",
    "pill_highlight": "pill_highlight",
    "brand_bar": "brand_bar",
    "pulse_pop": "pulse_pop",
    "fade_in": "fade_in",
    "news_ticker": "news_ticker",
    "impact": "impact",
    "progressive_reveal": "progressive_reveal",
}

ANIMATION_OPTIONS = [
    "none",
    "bounce",
    "underline",
    "box",
    "pop",
    "scale",
    "slide_left",
    "slide_up",
    "seamless_bounce",
    "highlighter_box_around",
    "blur_switch",
    "baby_earthquake",
    "glitch_infinite_zoom",
    "focus",
    "blur_in",
    "with_backdrop",
    "soft_landing",
    "baby_steps",
    "grow",
    "breathe",
    # Preset-facing names.
    "karaoke_sweep",
    "typewriter",
    "neon_glow",
    "conveyor_left",
    "punch",
    "pill_highlight",
    "brand_bar",
    "pulse_pop",
    "fade_in",
    "news_ticker",
    "impact",
    "progressive_reveal",
]

CAPTION_PRESETS: dict[str, CaptionPresetDefinition] = {
    "word_by_word_highlight": {
        "id": "word_by_word_highlight",
        "label": "Word-by-Word Highlight",
        "description": "Highlights each spoken word in real time for strong emphasis.",
        "captions": {
            "style": "word_by_word",
            "animation": "focus",
            "fontSize": 52,
            "fontWeight": "800",
            "strokeThickness": 7,
            "highlightColor": "#FFD400",
            "position": "middle",
            "linesPerPage": 1,
            "maxWordsPerLine": 3,
            "maxCharsPerCaption": 24,
        },
    },
    "karaoke_sweep": {
        "id": "karaoke_sweep",
        "label": "Karaoke Sweep",
        "description": "Uses a smooth sweep effect so words light up progressively.",
        "captions": {
            "style": "animated",
            "animation": "karaoke_sweep",
            "fontSize": 50,
            "fontFamily": "Poppins",
            "fontWeight": "700",
            "strokeColor": "#101010",
            "strokeThickness": 5,
            "highlightColor": "#00E5FF",
            "position": "bottom",
            "linesPerPage": 1,
            "maxWordsPerLine": 5,
            "maxCharsPerCaption": 36,
        },
    },
    "pop_animation": {
        "id": "pop_animation",
        "label": "Pop Animation",
        "description": "Words pop in with quick scaling for energetic delivery.",
        "captions": {
            "style": "animated",
            "animation": "pop",
            "fontSize": 54,
            "fontWeight": "800",
            "strokeThickness": 6,
            "highlightColor": "#FFDE59",
            "position": "bottom",
            "linesPerPage": 1,
            "maxWordsPerLine": 4,
            "maxCharsPerCaption": 30,
        },
    },
    "minimal_clean": {
        "id": "minimal_clean",
        "label": "Minimal Clean",
        "description": "Clean low-distraction captions with subtle styling.",
        "captions": {
            "style": "lowercase",
            "animation": "none",
            "fontSize": 42,
            "fontFamily": "Inter",
            "fontWeight": "500",
            "fontCase": "lowercase",
            "strokeThickness": 2,
            "shadowBlur": 1,
            "highlightColor": "#FFFFFF",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 6,
            "maxCharsPerCaption": 48,
        },
    },
    "neon_glow": {
        "id": "neon_glow",
        "label": "Neon Glow",
        "description": "Bright neon text with glow-like contrast for night edits.",
        "captions": {
            "style": "headline",
            "animation": "neon_glow",
            "fontSize": 50,
            "fontColor": "#39FF14",
            "fontFamily": "Poppins",
            "fontWeight": "700",
            "strokeColor": "#003322",
            "strokeThickness": 4,
            "shadowColor": "#00FFCC",
            "shadowX": 0,
            "shadowY": 0,
            "shadowBlur": 8,
            "highlightColor": "#00E5FF",
            "position": "middle",
            "linesPerPage": 2,
            "maxWordsPerLine": 4,
            "maxCharsPerCaption": 34,
        },
    },
    "typewriter_effect": {
        "id": "typewriter_effect",
        "label": "Typewriter Effect",
        "description": "Reveals text progressively to mimic a typing rhythm.",
        "captions": {
            "style": "progressive",
            "animation": "typewriter",
            "fontSize": 44,
            "fontFamily": "Inter",
            "fontWeight": "600",
            "strokeColor": "#1A1A1A",
            "strokeThickness": 3,
            "highlightColor": "#FFD166",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 5,
            "maxCharsPerCaption": 40,
        },
    },
    "bounce_in": {
        "id": "bounce_in",
        "label": "Bounce In",
        "description": "Captions bounce into place to add playful motion.",
        "captions": {
            "style": "animated",
            "animation": "bounce",
            "fontSize": 52,
            "fontWeight": "800",
            "strokeThickness": 6,
            "highlightColor": "#FFE066",
            "position": "bottom",
            "linesPerPage": 1,
            "maxWordsPerLine": 4,
            "maxCharsPerCaption": 30,
        },
    },
    "slide_up": {
        "id": "slide_up",
        "label": "Slide Up",
        "description": "Lines slide up from below for smooth transitions.",
        "captions": {
            "style": "grouped",
            "animation": "slide_up",
            "fontSize": 46,
            "fontFamily": "Inter",
            "fontWeight": "700",
            "strokeThickness": 4,
            "highlightColor": "#CDEBFF",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 5,
            "maxCharsPerCaption": 40,
        },
    },
    "center_word_focus": {
        "id": "center_word_focus",
        "label": "Center Word Focus",
        "description": "Keeps one key word centered at a time for attention control.",
        "captions": {
            "style": "word_by_word",
            "animation": "focus",
            "fontSize": 58,
            "fontFamily": "Poppins",
            "fontWeight": "900",
            "strokeThickness": 7,
            "highlightColor": "#FFEA00",
            "position": "middle",
            "linesPerPage": 1,
            "maxWordsPerLine": 2,
            "maxCharsPerCaption": 18,
        },
    },
    "conveyor_belt_ticker": {
        "id": "conveyor_belt_ticker",
        "label": "Conveyor Belt",
        "description": "Runs captions in a horizontal ticker flow like a conveyor belt.",
        "captions": {
            "style": "static",
            "animation": "conveyor_left",
            "fontSize": 36,
            "fontFamily": "Inter",
            "fontWeight": "600",
            "strokeThickness": 3,
            "highlightColor": "#FFB703",
            "position": "bottom",
            "linesPerPage": 1,
            "maxWordsPerLine": 8,
            "maxCharsPerCaption": 64,
        },
    },
    "bold_punch": {
        "id": "bold_punch",
        "label": "Bold Punch",
        "description": "Heavy impact captions punch each phrase for strong emphasis.",
        "captions": {
            "style": "animated",
            "animation": "punch",
            "fontSize": 60,
            "fontWeight": "900",
            "fontCase": "uppercase",
            "strokeThickness": 8,
            "highlightColor": "#FF3B30",
            "position": "middle",
            "linesPerPage": 1,
            "maxWordsPerLine": 3,
            "maxCharsPerCaption": 24,
        },
    },
    "soft_pill_highlight": {
        "id": "soft_pill_highlight",
        "label": "Soft Pill Highlight",
        "description": "Uses a soft rounded highlight feel behind text.",
        "captions": {
            "style": "grouped",
            "animation": "pill_highlight",
            "fontSize": 46,
            "fontColor": "#1F2937",
            "fontFamily": "Poppins",
            "fontWeight": "600",
            "strokeColor": "#FFFFFF",
            "strokeThickness": 2,
            "shadowBlur": 1,
            "highlightColor": "#FDE68A",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 5,
            "maxCharsPerCaption": 38,
        },
    },
    "classic_clean_outline": {
        "id": "classic_clean_outline",
        "label": "Classic Clean Outline",
        "description": "Traditional white captions with a strong black outline.",
        "captions": {
            "style": "static",
            "animation": "none",
            "fontSize": 48,
            "fontFamily": "Montserrat",
            "fontWeight": "700",
            "strokeThickness": 7,
            "highlightColor": "#FFD700",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 5,
            "maxCharsPerCaption": 42,
        },
    },
    "brand_bar": {
        "id": "brand_bar",
        "label": "Brand Bar",
        "description": "Caption text sits in a branded bar treatment.",
        "captions": {
            "style": "grouped",
            "animation": "brand_bar",
            "fontSize": 44,
            "fontFamily": "Inter",
            "fontWeight": "700",
            "strokeColor": "#0F172A",
            "strokeThickness": 6,
            "highlightColor": "#2563EB",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 5,
            "maxCharsPerCaption": 40,
        },
    },
    "energetic_pop_pulse": {
        "id": "energetic_pop_pulse",
        "label": "Energetic Pop + Pulse",
        "description": "Combines pop-ins with pulsing emphasis for high energy edits.",
        "captions": {
            "style": "animated",
            "animation": "pulse_pop",
            "fontSize": 56,
            "fontWeight": "800",
            "fontCase": "uppercase",
            "strokeThickness": 7,
            "highlightColor": "#FF9F1C",
            "position": "middle",
            "linesPerPage": 1,
            "maxWordsPerLine": 3,
            "maxCharsPerCaption": 24,
        },
    },
    "dramatic_fade_in": {
        "id": "dramatic_fade_in",
        "label": "Dramatic Fade In",
        "description": "Text fades in smoothly to match cinematic pacing.",
        "captions": {
            "style": "punctuated",
            "animation": "fade_in",
            "fontSize": 50,
            "fontColor": "#F8FAFC",
            "fontFamily": "Poppins",
            "fontWeight": "700",
            "strokeThickness": 4,
            "shadowX": 0,
            "shadowY": 3,
            "shadowBlur": 6,
            "highlightColor": "#94A3B8",
            "position": "middle",
            "linesPerPage": 2,
            "maxWordsPerLine": 4,
            "maxCharsPerCaption": 36,
        },
    },
    "news_ticker": {
        "id": "news_ticker",
        "label": "News Ticker",
        "description": "Compact ticker captions for fast informational updates.",
        "captions": {
            "style": "static",
            "animation": "news_ticker",
            "fontSize": 34,
            "fontFamily": "Inter",
            "fontWeight": "700",
            "fontCase": "uppercase",
            "strokeColor": "#111827",
            "strokeThickness": 3,
            "highlightColor": "#EF4444",
            "position": "top",
            "linesPerPage": 1,
            "maxWordsPerLine": 10,
            "maxCharsPerCaption": 72,
        },
    },
    "two_line_stylish": {
        "id": "two_line_stylish",
        "label": "Two-Line Stylish",
        "description": "Balanced two-line layout with modern spacing.",
        "captions": {
            "style": "two_line",
            "animation": "soft_landing",
            "fontSize": 48,
            "fontFamily": "Poppins",
            "fontWeight": "700",
            "highlightColor": "#22D3EE",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 4,
            "maxCharsPerCaption": 38,
        },
    },
    "uppercase_bold_impact": {
        "id": "uppercase_bold_impact",
        "label": "Uppercase Bold Impact",
        "description": "All-caps heavy captions built for high-contrast impact.",
        "captions": {
            "style": "uppercase",
            "animation": "impact",
            "fontSize": 58,
            "fontWeight": "900",
            "fontCase": "uppercase",
            "strokeThickness": 8,
            "highlightColor": "#FACC15",
            "position": "middle",
            "linesPerPage": 1,
            "maxWordsPerLine": 3,
            "maxCharsPerCaption": 22,
        },
    },
    "progressive_reveal": {
        "id": "progressive_reveal",
        "label": "Progressive Reveal",
        "description": "Builds each phrase word by word to keep anticipation high.",
        "captions": {
            "style": "progressive",
            "animation": "progressive_reveal",
            "fontSize": 46,
            "fontFamily": "Inter",
            "fontWeight": "700",
            "strokeThickness": 4,
            "highlightColor": "#34D399",
            "position": "bottom",
            "linesPerPage": 2,
            "maxWordsPerLine": 5,
            "maxCharsPerCaption": 44,
        },
    },
}

CAPTION_TEMPLATE_DEFAULTS: CaptionTemplate = {
    "show": True,
    "style": "grouped",
    "animation": "none",
    "fontSize": 44,
    "fontColor": "#FFFFFF",
    "fontFamily": "Montserrat",
    "fontWeight": "black",
    "fontCase": "as_typed",
    "italic": False,
    "underline": False,
    "strokeColor": "#000000",
    "strokeThickness": 6,
    "shadowColor": "#000000FF",
    "shadowX": 2,
    "shadowY": 2,
    "shadowBlur": 2,
    "highlightColor": "#FFD700",
    "position": "auto",
    "linesPerPage": 2,
    "maxWordsPerLine": 4,
    # UI helper for line-breaking heuristics (not used by renderer yet).
    "maxCharsPerCaption": 42,
}


