"""MinIO S3-compatible client singleton."""

from __future__ import annotations

import json
import logging
import os
from datetime import timedelta

from minio import Minio

from config import (
    MINIO_ACCESS_KEY,
    MINIO_AVATARS_BUCKET,
    MINIO_CLIPS_BUCKET,
    MINIO_ENDPOINT,
    MINIO_LAYOUTS_BUCKET,
    MINIO_PUBLIC_ENDPOINT,
    MINIO_RAW_VIDEOS_BUCKET,
    MINIO_REGION,
    MINIO_SECRET_KEY,
    MINIO_SECURE,
)

logger = logging.getLogger(__name__)

_client: Minio | None = None
_public_client: Minio | None = None
_storage_initialized = False


def get_minio_client() -> Minio:
    """Return a MinIO client for internal (server-to-server) operations."""
    global _client
    if _client is None:
        _client = Minio(
            endpoint=MINIO_ENDPOINT,
            access_key=MINIO_ACCESS_KEY,
            secret_key=MINIO_SECRET_KEY,
            secure=MINIO_SECURE,
            region=MINIO_REGION,
        )
    return _client


def get_minio_public_client() -> Minio:
    """Return a MinIO client configured with the public-facing endpoint.

    Presigned URLs generated by this client will point to the public
    endpoint so browsers can reach them directly.  Falls back to the
    internal client when ``MINIO_PUBLIC_ENDPOINT`` is not set.
    """
    global _public_client
    if _public_client is not None:
        return _public_client

    if not MINIO_PUBLIC_ENDPOINT:
        _public_client = get_minio_client()
        return _public_client

    public_endpoint = MINIO_PUBLIC_ENDPOINT
    public_secure = MINIO_SECURE
    # Infer scheme from the URL if it looks like a full URL.
    if public_endpoint.startswith("https://"):
        public_endpoint = public_endpoint.removeprefix("https://").rstrip("/")
        public_secure = True
    elif public_endpoint.startswith("http://"):
        public_endpoint = public_endpoint.removeprefix("http://").rstrip("/")
        public_secure = False

    _public_client = Minio(
        endpoint=public_endpoint,
        access_key=MINIO_ACCESS_KEY,
        secret_key=MINIO_SECRET_KEY,
        secure=public_secure,
        region=MINIO_REGION,
    )
    return _public_client


def _bucket_policy(*, bucket_name: str, public_read: bool) -> str:
    statements: list[dict[str, object]] = []
    if public_read:
        statements.append(
            {
                "Effect": "Allow",
                "Principal": {"AWS": ["*"]},
                "Action": ["s3:GetObject"],
                "Resource": [f"arn:aws:s3:::{bucket_name}/*"],
            }
        )

    return json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": statements,
        }
    )


def _ensure_bucket_policy(client: Minio, bucket_name: str, *, public_read: bool) -> None:
    desired_policy = _bucket_policy(bucket_name=bucket_name, public_read=public_read)
    try:
        current_policy = client.get_bucket_policy(bucket_name)
    except Exception:
        current_policy = None

    if current_policy == desired_policy:
        return

    client.set_bucket_policy(bucket_name, desired_policy)
    logger.info(
        "Applied MinIO bucket policy for %s (public_read=%s)",
        bucket_name,
        public_read,
    )


def ensure_buckets() -> None:
    """Create required buckets if they don't exist."""
    client = get_minio_client()
    bucket_specs = (
        (MINIO_CLIPS_BUCKET, False),
        (MINIO_RAW_VIDEOS_BUCKET, False),
        (MINIO_AVATARS_BUCKET, True),
        (MINIO_LAYOUTS_BUCKET, False),
    )
    for bucket_name, public_read in bucket_specs:
        if not client.bucket_exists(bucket_name):
            client.make_bucket(bucket_name, location=MINIO_REGION)
            logger.info("Created MinIO bucket: %s", bucket_name)
        _ensure_bucket_policy(client, bucket_name, public_read=public_read)


def initialize_minio_storage() -> None:
    """Ensure MinIO buckets and policies exist exactly once per process."""
    global _storage_initialized
    if _storage_initialized:
        return

    if str(os.getenv("MINIO_SKIP_STARTUP_READINESS") or "").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }:
        logger.info("Skipping MinIO startup readiness checks")
        _storage_initialized = True
        return

    ensure_buckets()
    _storage_initialized = True


def download_object(bucket: str, object_name: str) -> bytes:
    """Download an object from MinIO and return its contents as bytes."""
    client = get_minio_client()
    response = client.get_object(bucket, object_name)
    try:
        return response.read()
    finally:
        response.close()
        response.release_conn()


def presigned_get_url(
    bucket: str,
    object_name: str,
    *,
    expires_seconds: int = 3600,
    response_headers: dict[str, str] | None = None,
) -> str:
    """Generate a presigned GET URL using the public-facing endpoint."""
    client = get_minio_public_client()
    return client.presigned_get_object(
        bucket,
        object_name,
        expires=timedelta(seconds=expires_seconds),
        response_headers=response_headers,
    )
